[tool.poetry]
name = "finetuning-pretrained-model"
version = "0.1.0"
description = ""
authors = ["Thierry <thierrysantoos123@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
